### ISSUE TITLE
Implement `Submission` model

### ISSUE THREAD

**Issue by pierremonico** [healthdesk-hackathon/backend#2]
Implement the model representing a submission from a patient. 
The naming is to be defined (avoid `Form` since this is misleading in the Django context).

Framing conditions:

- [The primary key should be set to be a UID.](https://books.agiliq.com/projects/django-orm-cookbook/en/latest/uuid.html)
- A patient can potentially submit data several times
- Some fields will be mandatory, others won't (in the context of a multi-step form) 
- This model will mostly hold reverse references to other models (that basically represent the steps of the form), e.g. the Covid-19 symptoms model, but that doesn't ave to be written in the model (FKs are on the others).
- There should one field for some sort of unique identifier (phone number, insurance number, email address etc.) 
- There should be one field for selecting the identifier type (cf. suggestions above - TBD)
- All linked fields are optional but that doesn't matter

Expose the model in the API (use a Modelviewset so all HTTP methods are available).

**Comment by philayres** [comment]
I have put together this, with the following hierarchy of models:

                    master
                         |
        submission           admission
        |              |
    person    phone

admission has been addedd, to represent the barcode wrist tag, etc, since represents the actual admission (entry) into the hospital system, rather than just an online form submission. 

Will do a PR now.
